---
    - name: Update apt packages cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Python pip (required for Docker Compose)
      apt:
        name: python3-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        executable: pip3  

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version

    - debug:
        msg: "Docker Compose installed, version {{ docker_compose_version.stdout }}"

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
